function createCharacterPlaceholder(name, colorA, colorB) {
  var safeName = escapeXml(name);
  var svg =
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 520">' +
    '<defs>' +
    '<linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%">' +
    '<stop offset="0%" stop-color="' + colorA + '"/>' +
    '<stop offset="100%" stop-color="' + colorB + '"/>' +
    '</linearGradient>' +
    '</defs>' +
    '<rect width="480" height="520" rx="44" fill="url(#g)"/>' +
    '<circle cx="380" cy="95" r="66" fill="rgba(255,255,255,0.16)"/>' +
    '<circle cx="90" cy="430" r="74" fill="rgba(255,255,255,0.12)"/>' +
    '<text x="50%" y="47%" dominant-baseline="middle" text-anchor="middle" fill="white" font-size="72" font-family="PingFang SC, Microsoft YaHei, sans-serif" font-weight="700">' +
    safeName +
    '</text>' +
    '<text x="50%" y="69%" dominant-baseline="middle" text-anchor="middle" fill="rgba(255,255,255,0.8)" font-size="26" font-family="PingFang SC, Microsoft YaHei, sans-serif">角色图片占位</text>' +
    '</svg>';

  return 'data:image/svg+xml;charset=UTF-8,' + encodeURIComponent(svg);
}

function escapeXml(text) {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

var CHARACTER_IMAGE_MAP = {
  "walter-white": "images/walter-white.jpg",
  "sheldon": "images/sheldon.jpg",
  "joker": "images/joker.jpg",
  "iron-man": "images/iron-man.jpg",
  "sherlock": "images/sherlock.jpg",
  "saul": "images/saul.jpg",
  "luffy": "images/luffy.jpg",
  "naruto": "images/naruto.jpg",
  "sasuke": "images/sasuke.jpg",
  "ichigo": "images/ichigo.jpg",
  "gojo": "images/gojo.jpg",
  "shinji": "images/shinji.jpg",
  "light": "images/light.jpg",
  "yuji": "images/yuji.jpg",
  "eren": "images/eren.jpg",
  "deadpool": "images/deadpool.jpg",
  "batman": "images/batman.jpg",
  "jack-sparrow": "images/jack-sparrow.jpg",
  "house": "images/house.jpg",
  "l": "images/L.jpg",
  "lelouch": "images/lelouch.jpg",
  "the-deep": "images/the-deep.jpg",
  "homelander": "images/homelander.jpg",
  "sukuna": "images/sukuna.jpg",
  "invincible": "images/invincible.jpg",
  "omni_man": "images/omni_man.jpg",
  "gilgamesh": "images/gilgamesh.jpg",
  "muzan": "images/muzan.jpg",
  "tanjiro": "images/tanjiro.jpg",
  "denji": "images/denji.jpg",
  "makima": "images/makima.jpg",
  "captain_america": "images/captain_america.jpg",
  "conan": "images/conan.jpg",
  "kaito_kid": "images/kaito_kid.jpg",
  "count_of_monte_cristo": "images/count_of_monte_cristo.jpg",
  "joseph_joestar": "images/joseph_joestar.jpg",
  "hannibal_lecter": "images/hannibal_lecter.jpg",
  "peter_griffin": "images/peter_griffin.png",
  "brian_griffin": "images/brian_griffin.jpg",
  "sonny_hayes": "images/sonny_hayes.jpg",
  "shaun_murphy": "images/shaun_murphy.jpg",
  "leon_kennedy": "images/leon_kennedy.jpg",
  "ada_wong": "images/ada_wong.jpg",
  "chris_redfield": "images/chris_redfield.jpg",
  "dio_brando": "images/dio_brando.jpg",
  "yoshikage_kira": "images/yoshikage_kira.jpg",
  "elon_musk": "images/elon_musk.jpg",
  "tohsaka_rin": "images/tohsaka_rin.jpg",
  "asuka_langley": "images/asuka_langley.jpg"
};

window.characters = [
  {
    id: "walter-white",
    name: "老白",
    originalName: "Walter White",
    source: "绝命毒师",
    image: createCharacterPlaceholder("老白", "#723d46", "#3a0f1b"),
    description: "你擅长在压力里做出精密判断，表面克制，内里野心很强，一旦认定目标就会持续推进。",
    traits: { rational: 90, emotional: 60, impulsive: 40, calm: 80, social: 36, solitary: 78, orderly: 72, rebellious: 66, ambitious: 96, altruistic: 22, humorous: 18, disguised: 60, moral: 33, conformist: 21, execution: 94, romance: 14, dependency: 8, realism: 95, absurdity: 16, courage: 63, egoism: 93, empathy: 24, decisiveness: 92, stressTolerance: 88 }
  },
  {
    id: "sheldon",
    name: "谢尔顿",
    originalName: "Sheldon Cooper",
    source: "生活大爆炸",
    image: createCharacterPlaceholder("谢尔顿", "#4d7ea8", "#20395a"),
    description: "理性和规则感极强，思维精确到细节，情绪表达不多，但对自己认定的秩序非常坚持。",
    traits: { rational: 97, emotional: 16, impulsive: 10, calm: 20, social: 10, solitary: 88, orderly: 95, rebellious: 16, ambitious: 99, altruistic: 80, humorous: 36, disguised: 14, moral: 74, conformist: 66, execution: 70, romance: 60, dependency: 67, realism: 81, absurdity: 39, courage: 18, egoism: 74, empathy: 28, decisiveness: 48, stressTolerance: 27 }
  },
  {
    id: "joker",
    name: "小丑",
    originalName: "Joker",
    source: "蝙蝠侠：黑暗骑士",
    image: createCharacterPlaceholder("小丑", "#7b2d8e", "#1f102f"),
    description: "不爱走常规路线，喜欢打乱牌桌和既定规则，脑回路跳脱，危险感和魅力并存。",
    traits: { rational: 58, emotional: 72, impulsive: 85, calm: 32, social: 79, solitary: 46, orderly: 4, rebellious: 98, ambitious: 81, altruistic: 4, humorous: 80, disguised: 91, moral: 2, conformist: 1, execution: 67, romance: 8, dependency: 5, realism: 19, absurdity: 97, courage: 74, egoism: 94, empathy: 6, decisiveness: 89, stressTolerance: 71 }
  },
  {
    id: "iron-man",
    name: "钢铁侠",
    originalName: "Tony Stark",
    source: "钢铁侠",
    image: createCharacterPlaceholder("钢铁侠", "#d88b17", "#7d1d17"),
    description: "你有锋利的大脑和强烈的个人风格，能扛事也敢出头，嘴上轻松，行动上很顶。",
    traits: { rational: 86, emotional: 44, impulsive: 56, calm: 61, social: 84, solitary: 21, orderly: 42, rebellious: 74, ambitious: 88, altruistic: 79, humorous: 92, disguised: 29, moral: 75, conformist: 11, execution: 91, romance: 48, dependency: 24, realism: 73, absurdity: 61, courage: 89, egoism: 78, empathy: 52, decisiveness: 90, stressTolerance: 84 }
  },
  {
    id: "sherlock",
    name: "福尔摩斯",
    originalName: "Sherlock Holmes",
    source: "神探夏洛克",
    image: createCharacterPlaceholder("福尔摩斯", "#596d7a", "#1f2830"),
    description: "你观察力和判断力都很强，面对复杂局面反而更冷静，喜欢用脑子而不是情绪解决问题。",
    traits: { rational: 98, emotional: 17, impulsive: 22, calm: 88, social: 31, solitary: 84, orderly: 70, rebellious: 59, ambitious: 72, altruistic: 46, humorous: 38, disguised: 51, moral: 67, conformist: 14, execution: 86, romance: 8, dependency: 7, realism: 88, absurdity: 24, courage: 58, egoism: 63, empathy: 31, decisiveness: 86, stressTolerance: 79 }
  },
  {
    id: "saul",
    name: "索尔·古德曼",
    originalName: "Saul Goodman",
    source: "风骚律师",
    image: createCharacterPlaceholder("索尔", "#b66f1f", "#562813"),
    description: "你反应快，会说会转弯，擅长在灰色地带找解法，表面圆滑，实际执行力并不差。",
    traits: { rational: 89, emotional: 43, impulsive: 48, calm: 52, social: 93, solitary: 14, orderly: 24, rebellious: 81, ambitious: 77, altruistic: 31, humorous: 93, disguised: 88, moral: 26, conformist: 8, execution: 74, romance: 28, dependency: 19, realism: 79, absurdity: 76, courage: 57, egoism: 83, empathy: 27, decisiveness: 73, stressTolerance: 58 }
  },
  {
    id: "luffy",
    name: "路飞",
    originalName: "Monkey D. Luffy",
    source: "海贼王",
    image: createCharacterPlaceholder("路飞", "#e0841b", "#9a2f13"),
    description: "你重感情、行动快、认定伙伴就会一路护到底，很多决定都来自本能和热血。",
    traits: { rational: 18, emotional: 88, impulsive: 97, calm: 14, social: 76, solitary: 5, orderly: 8, rebellious: 95, ambitious: 58, altruistic: 88, humorous: 62, disguised: 3, moral: 74, conformist: 2, execution: 72, romance: 5, dependency: 14, realism: 12, absurdity: 54, courage: 98, egoism: 18, empathy: 70, decisiveness: 82, stressTolerance: 73 }
  },
  {
    id: "naruto",
    name: "鸣人",
    originalName: "Naruto Uzumaki",
    source: "火影忍者",
    image: createCharacterPlaceholder("鸣人", "#f5a623", "#f76b1c"),
    description: "你热情外放，认准的人和信念都不会轻易放弃，越被低估，越能打出自己的节奏。",
    traits: { rational: 32, emotional: 91, impulsive: 79, calm: 24, social: 78, solitary: 8, orderly: 28, rebellious: 68, ambitious: 68, altruistic: 84, humorous: 54, disguised: 8, moral: 79, conformist: 9, execution: 74, romance: 28, dependency: 52, realism: 24, absurdity: 36, courage: 83, egoism: 18, empathy: 79, decisiveness: 73, stressTolerance: 61 }
  },
  {
    id: "sasuke",
    name: "佐助",
    originalName: "Sasuke Uchiha",
    source: "火影忍者",
    image: createCharacterPlaceholder("佐助", "#5b6290", "#1d1f38"),
    description: "你有明显的目标导向，不喜欢过度解释，很多情绪都藏着走，行动比表达更有分量。",
    traits: { rational: 68, emotional: 58, impulsive: 39, calm: 61, social: 14, solitary: 94, orderly: 38, rebellious: 81, ambitious: 87, altruistic: 18, humorous: 8, disguised: 68, moral: 42, conformist: 5, execution: 84, romance: 9, dependency: 8, realism: 58, absurdity: 10, courage: 72, egoism: 79, empathy: 12, decisiveness: 79, stressTolerance: 72 }
  },
  {
    id: "ichigo",
    name: "黑崎一护",
    originalName: "Ichigo Kurosaki",
    source: "死神",
    image: createCharacterPlaceholder("一护", "#d96a28", "#422029"),
    description: "你看上去没那么爱张扬，但关键时刻很能扛，保护欲和行动力都很强，属于闷着顶的人。",
    traits: { rational: 54, emotional: 71, impulsive: 58, calm: 42, social: 36, solitary: 52, orderly: 36, rebellious: 59, ambitious: 48, altruistic: 74, humorous: 21, disguised: 19, moral: 71, conformist: 15, execution: 72, romance: 18, dependency: 21, realism: 43, absurdity: 14, courage: 79, egoism: 31, empathy: 66, decisiveness: 66, stressTolerance: 61 }
  },
  {
    id: "gojo",
    name: "五条悟",
    originalName: "Satoru Gojo",
    source: "咒术回战",
    image: createCharacterPlaceholder("五条悟", "#9cd5ff", "#3457a1"),
    description: "自带强势气场，聪明、松弛、会抽象，真正需要出手的时候又能迅速压住场面，但有可能会变成2.5条悟。",
    traits: { rational: 61, emotional: 48, impulsive: 59, calm: 77, social: 83, solitary: 17, orderly: 34, rebellious: 71, ambitious: 75, altruistic: 69, humorous: 88, disguised: 32, moral: 67, conformist: 9, execution: 87, romance: 21, dependency: 14, realism: 46, absurdity: 82, courage: 92, egoism: 57, empathy: 49, decisiveness: 86, stressTolerance: 88 }
  },
  {
    id: "shinji",
    name: "碇真嗣",
    originalName: "Shinji Ikari",
    source: "新世纪福音战士",
    image: createCharacterPlaceholder("碇真嗣", "#98a4b6", "#475266"),
    description: "内心敏感，容易反复自省，很多情绪会先压在心里，真正触到底线时又会突然爆发。",
    traits: { rational: 41, emotional: 89, impulsive: 37, calm: 34, social: 15, solitary: 86, orderly: 49, rebellious: 38, ambitious: 22, altruistic: 66, humorous: 8, disguised: 63, moral: 71, conformist: 69, execution: 42, romance: 58, dependency: 83, realism: 52, absurdity: 36, courage: 29, egoism: 23, empathy: 82, decisiveness: 18, stressTolerance: 14 }
  },
  {
    id: "light",
    name: "夜神月",
    originalName: "Light Yagami",
    source: "死亡笔记",
    image: createCharacterPlaceholder("夜神月", "#8f463f", "#231316"),
    description: "目标感强，脑子转得快，擅长布局和伪装，既有精英感，也有极强的掌控欲。",
    traits: { rational: 94, emotional: 24, impulsive: 21, calm: 86, social: 84, solitary: 58, orderly: 73, rebellious: 52, ambitious: 98, altruistic: 12, humorous: 8, disguised: 95, moral: 18, conformist: 39, execution: 97, romance: 5, dependency: 9, realism: 91, absurdity: 14, courage: 72, egoism: 97, empathy: 8, decisiveness: 96, stressTolerance: 82 }
  },
  
  {
    id: "yuji",
    name: "虎杖悠仁",
    originalName: "Yuji Itadori",
    source: "咒术回战",
    image: createCharacterPlaceholder("虎杖", "#f08b72", "#783d63"),
    description: "天然带着亲和力，愿意为别人出力，虽然会冲动，但本质上很真诚，也很能扛责任。",
    traits: { rational: 41, emotional: 85, impulsive: 73, calm: 41, social: 81, solitary: 12, orderly: 37, rebellious: 59, ambitious: 48, altruistic: 94, humorous: 58, disguised: 9, moral: 87, conformist: 21, execution: 78, romance: 26, dependency: 38, realism: 39, absurdity: 33, courage: 89, egoism: 19, empathy: 91, decisiveness: 71, stressTolerance: 61 }
  },
  {
    id: "eren",
    name: "艾伦",
    originalName: "Eren Yeager",
    source: "进击的巨人",
    image: createCharacterPlaceholder("艾伦", "#4c6133", "#1f2712"),
    description: "你有极强的执念和行动爆发力，对想守护的人与事会投入全部，但情绪也容易被目标点燃。",
    traits: { rational: 68, emotional: 87, impulsive: 83, calm: 24, social: 43, solitary: 52, orderly: 18, rebellious: 94, ambitious: 82, altruistic: 58, humorous: 14, disguised: 87, moral: 44, conformist: 4, execution: 89, romance: 83, dependency: 71, realism: 38, absurdity: 31, courage: 97, egoism: 76, empathy: 43, decisiveness: 88, stressTolerance: 89 }
  },
  {
    id: "deadpool",
    name: "死侍",
    originalName: "Deadpool",
    source: "死侍",
    image: createCharacterPlaceholder("死侍", "#d13438", "#2d0f18"),
    description: "嘴快、脑洞大、风格不按牌理出牌，表面玩世不恭，实际上很清楚自己在护什么。",
    traits: { rational: 47, emotional: 63, impulsive: 88, calm: 33, social: 86, solitary: 14, orderly: 7, rebellious: 96, ambitious: 42, altruistic: 68, humorous: 99, disguised: 71, moral: 56, conformist: 2, execution: 71, romance: 34, dependency: 17, realism: 34, absurdity: 99, courage: 86, egoism: 69, empathy: 54, decisiveness: 82, stressTolerance: 66 }
  },
  {
    id: "batman",
    name: "蝙蝠侠",
    originalName: "Batman",
    source: "蝙蝠侠",
    image: createCharacterPlaceholder("蝙蝠侠", "#3f4858", "#12161d"),
    description: "你克制、自律、习惯独自扛事，思考周密，情绪藏得深，但面对责任从不含糊。",
    traits: { rational: 89, emotional: 34, impulsive: 20, calm: 87, social: 29, solitary: 89, orderly: 81, rebellious: 57, ambitious: 76, altruistic: 81, humorous: 12, disguised: 84, moral: 86, conformist: 17, execution: 95, romance: 16, dependency: 12, realism: 88, absurdity: 8, courage: 95, egoism: 52, empathy: 58, decisiveness: 94, stressTolerance: 93 }
  },
  {
    id: "jack-sparrow",
    name: "杰克船长",
    originalName: "Jack Sparrow",
    source: "加勒比海盗",
    image: createCharacterPlaceholder("杰克", "#8a5b2b", "#3d2314"),
    description: "你有很强的临场反应和生存智慧，看起来松散随性，实际上比多数人更懂得怎么翻盘。",
    traits: { rational: 63, emotional: 55, impulsive: 67, calm: 52, social: 88, solitary: 19, orderly: 9, rebellious: 91, ambitious: 61, altruistic: 37, humorous: 91, disguised: 89, moral: 33, conformist: 3, execution: 68, romance: 26, dependency: 21, realism: 43, absurdity: 93, courage: 71, egoism: 73, empathy: 29, decisiveness: 69, stressTolerance: 58 }
  },
  {
    id: "house",
    name: "豪斯医生",
    originalName: "Dr. House",
    source: "豪斯医生",
    image: createCharacterPlaceholder("豪斯", "#7689a4", "#263246"),
    description: "你擅长看穿问题本质，不爱社交礼仪那一套，嘴上毒，判断准，很多事最后还得靠你兜住。",
    traits: { rational: 95, emotional: 21, impulsive: 28, calm: 79, social: 24, solitary: 86, orderly: 43, rebellious: 76, ambitious: 69, altruistic: 54, humorous: 84, disguised: 39, moral: 63, conformist: 6, execution: 84, romance: 7, dependency: 8, realism: 96, absurdity: 57, courage: 64, egoism: 87, empathy: 22, decisiveness: 86, stressTolerance: 72 }
  },
  {
    id: "l",
    name: "L",
    originalName: "L",
    source: "死亡笔记",
    image: createCharacterPlaceholder("L", "#bcc2cc", "#555d68"),
    description: "你对信息和逻辑非常敏感，喜欢独立判断，不容易被气氛带走，更相信自己的推理链条。",
    traits: { rational: 99, emotional: 18, impulsive: 11, calm: 78, social: 16, solitary: 93, orderly: 69, rebellious: 44, ambitious: 61, altruistic: 52, humorous: 14, disguised: 55, moral: 71, conformist: 12, execution: 79, romance: 5, dependency: 6, realism: 87, absurdity: 41, courage: 46, egoism: 58, empathy: 33, decisiveness: 76, stressTolerance: 67 }
  },
  {
    id: "lelouch",
    name: "鲁路修",
    originalName: "Lelouch",
    source: "反叛的鲁路修",
    image: createCharacterPlaceholder("鲁路修", "#6b4aa0", "#1f1737"),
    description: "战略意识强，擅长隐藏真实意图，会为了目标承担代价，冷静与情感常常同时拉扯你。",
    traits: { rational: 92, emotional: 57, impulsive: 26, calm: 81, social: 57, solitary: 49, orderly: 36, rebellious: 89, ambitious: 95, altruistic: 53, humorous: 22, disguised: 98, moral: 46, conformist: 4, execution: 93, romance: 37, dependency: 41, realism: 74, absurdity: 29, courage: 84, egoism: 82, empathy: 46, decisiveness: 91, stressTolerance: 86 }
  },
  {
    id: "the-deep",
    name: "深海",
    originalName: "The Deep",
    source: "黑袍纠察队",
    image: createCharacterPlaceholder("深海", "#4ca0d8", "#17405e"),
    description: "不是主角感不足，你是主角一登场就先摔进水里的那个小丑。",
    traits: {
      rational: 29,
      emotional: 76,
      impulsive: 87,
      calm: 44,
      social: 83,
      solitary: 21,
      orderly: 48,
      rebellious: 36,
      ambitious: 62,
      altruistic: 24,
      humorous: 52,
      disguised: 71,
      moral: 29,
      conformist: 81,
      execution: 35,
      romance: 58,
      dependency: 86,
      realism: 41,
      absurdity: 84,
      courage: 11,
      egoism: 72,
      empathy: 37,
      decisiveness: 28,
      stressTolerance: 33
    }
  },
  {
    id: "homelander",
    name: "祖国人",
    originalName: "Homelander",
    source: "黑袍纠察队",
    image: createCharacterPlaceholder("祖国人", "#d9b448", "#7d1426"),
    description: "超级巨婴，只是想让全世界看你爱你。",
    traits: {
      rational: 72,
      emotional: 88,
      impulsive: 82,
      calm: 18,
      social: 66,
      solitary: 42,
      orderly: 61,
      rebellious: 74,
      ambitious: 97,
      altruistic: 6,
      humorous: 28,
      disguised: 91,
      moral: 12,
      conformist: 34,
      execution: 90,
      romance: 18,
      dependency: 89,
      realism: 68,
      absurdity: 77,
      courage: 20,
      egoism: 99,
      empathy: 4,
      decisiveness: 96,
      stressTolerance: 73
    }
  },
  {
    id: "sukuna",
    name: "两面宿傩",
    originalName: "Ryomen Sukuna",
    source: "咒术回战",
    image: createCharacterPlaceholder("宿傩", "#c0435e", "#30090f"),
    description: "别人是有点自我，你是恨不得把世界都写成自己的菜单。",
    traits: {
      rational: 78,
      emotional: 34,
      impulsive: 71,
      calm: 86,
      social: 18,
      solitary: 91,
      orderly: 22,
      rebellious: 97,
      ambitious: 88,
      altruistic: 0,
      humorous: 36,
      disguised: 41,
      moral: 1,
      conformist: 0,
      execution: 95,
      romance: 0,
      dependency: 3,
      realism: 84,
      absurdity: 74,
      courage: 99,
      egoism: 100,
      empathy: 0,
      decisiveness: 98,
      stressTolerance: 99
    }
  },
  {
    id: "invincible",
    name: "无敌少侠",
    originalName: "Invincible",
    source: "无敌少侠",
    image: createCharacterPlaceholder("无敌少侠", "#f2d15b", "#b33b3f"),
    description: "不是不清醒，是每次都想当英雄，结果顺便把自己也打进icu。",
    traits: {
      rational: 58,
      emotional: 82,
      impulsive: 74,
      calm: 46,
      social: 71,
      solitary: 33,
      orderly: 57,
      rebellious: 69,
      ambitious: 61,
      altruistic: 88,
      humorous: 49,
      disguised: 29,
      moral: 91,
      conformist: 38,
      execution: 79,
      romance: 72,
      dependency: 67,
      realism: 44,
      absurdity: 41,
      courage: 92,
      egoism: 27,
      empathy: 86,
      decisiveness: 68,
      stressTolerance: 64
    }
  },
  {
    id: "omni_man",
    name: "全能侠",
    originalName: "Omni-Man",
    source: "无敌少侠",
    image: createCharacterPlaceholder("全能侠", "#b84a3c", "#1f2430"),
    description: "你极其看重结果、秩序和力量，做事果断，执行力强，面对高压局面也很少失控。你不太会被情绪牵着走，更习惯站在更高的位置判断局势，决定什么值得保留，什么应该被牺牲。你给人的感觉往往不是温和，而是强大、冷硬，甚至带着一种不容反驳的压迫感。",
    traits: {
      rational: 86,
      emotional: 24,
      impulsive: 29,
      calm: 93,
      social: 61,
      solitary: 57,
      orderly: 79,
      rebellious: 46,
      ambitious: 94,
      altruistic: 17,
      humorous: 12,
      disguised: 84,
      moral: 26,
      conformist: 58,
      execution: 99,
      romance: 14,
      dependency: 11,
      realism: 96,
      absurdity: 10,
      courage: 99,
      egoism: 95,
      empathy: 8,
      decisiveness: 99,
      stressTolerance: 99
    }
  },
  {
    id: "gilgamesh",
    name: "金闪闪",
    originalName: "Gilgamesh",
    source: "Fate",
    image: createCharacterPlaceholder("金闪闪", "#d4b24c", "#5a1f1f"),
    description: "自信得近乎傲慢，习惯用居高临下的视角审视周围的人和事，但也经常因此失败",
    traits: {
      rational: 79,
      emotional: 46,
      impulsive: 58,
      calm: 82,
      social: 62,
      solitary: 71,
      orderly: 54,
      rebellious: 86,
      ambitious: 97,
      altruistic: 21,
      humorous: 34,
      disguised: 23,
      moral: 29,
      conformist: 6,
      execution: 88,
      romance: 18,
      dependency: 5,
      realism: 73,
      absurdity: 39,
      courage: 98,
      egoism: 99,
      empathy: 11,
      decisiveness: 95,
      stressTolerance: 93
    }
  },
  {
    id: "muzan",
    name: "无惨",
    originalName: "Muzan Kibutsuji",
    source: "鬼灭之刃",
    image: createCharacterPlaceholder("无惨", "#6b1f2a", "#121212"),
    description: "控制欲强，警惕心重，做事狠且很少信任别人。你给人的感觉危险、压迫、难以接近。",
    traits: {
      rational: 84,
      emotional: 41,
      impulsive: 36,
      calm: 81,
      social: 52,
      solitary: 74,
      orderly: 77,
      rebellious: 63,
      ambitious: 96,
      altruistic: 1,
      humorous: 6,
      disguised: 95,
      moral: 0,
      conformist: 18,
      execution: 93,
      romance: 0,
      dependency: 4,
      realism: 97,
      absurdity: 21,
      courage: 38,
      egoism: 100,
      empathy: 0,
      decisiveness: 94,
      stressTolerance: 79
    }
  },
  {
    id: "tanjiro",
    name: "炭治郎",
    originalName: "Tanjiro Kamado",
    source: "鬼灭之刃",
    image: createCharacterPlaceholder("炭治郎", "#2f6b4f", "#2a1f1a"),
    description: "你温柔、坚韧、共情力强，很少只考虑自己。你给人的感觉真诚、可靠，又很能扛事。",
    traits: {
      rational: 63,
      emotional: 88,
      impulsive: 43,
      calm: 78,
      social: 61,
      solitary: 39,
      orderly: 68,
      rebellious: 34,
      ambitious: 52,
      altruistic: 97,
      humorous: 24,
      disguised: 9,
      moral: 98,
      conformist: 59,
      execution: 89,
      romance: 12,
      dependency: 36,
      realism: 58,
      absurdity: 8,
      courage: 96,
      egoism: 3,
      empathy: 99,
      decisiveness: 84,
      stressTolerance: 91
    }
  },
  {
    id: "denji",
    name: "电次",
    originalName: "Denji",
    source: "电锯人",
    image: createCharacterPlaceholder("电次", "#c86a2a", "#2b2b2b"),
    description: "常常被欲望和情绪推着往前走。你看起来不复杂，但真到硬扛的时候也很能撑。",
    traits: {
      rational: 10,
      emotional: 84,
      impulsive: 92,
      calm: 21,
      social: 58,
      solitary: 37,
      orderly: 14,
      rebellious: 81,
      ambitious: 34,
      altruistic: 66,
      humorous: 63,
      disguised: 8,
      moral: 41,
      conformist: 17,
      execution: 72,
      romance: 95,
      dependency: 91,
      realism: 52,
      absurdity: 89,
      courage: 87,
      egoism: 71,
      empathy: 54,
      decisiveness: 76,
      stressTolerance: 78
    }
  },
  {
    id: "makima",
    name: "玛奇玛",
    originalName: "Makima",
    source: "电锯人",
    image: createCharacterPlaceholder("玛奇玛", "#b35a5a", "#d8c9b8"),
    description: "你冷静、强势、控制欲很强，习惯站在更高的位置安排一切。你给人的感觉温和克制，但压迫感很重。",
    traits: {
      rational: 91,
      emotional: 22,
      impulsive: 12,
      calm: 97,
      social: 74,
      solitary: 53,
      orderly: 86,
      rebellious: 44,
      ambitious: 98,
      altruistic: 9,
      humorous: 11,
      disguised: 98,
      moral: 18,
      conformist: 52,
      execution: 99,
      romance: 6,
      dependency: 3,
      realism: 94,
      absurdity: 14,
      courage: 90,
      egoism: 97,
      empathy: 8,
      decisiveness: 98,
      stressTolerance: 98
    }
  },
  {
    id: "captain_america",
    name: "美国队长",
    originalName: "Captain America",
    source: "漫威",
    image: createCharacterPlaceholder("美国队长", "#3b5f9b", "#b33a3a"),
    description: "愿意在关键时刻站出来。你给人的感觉可靠、坚定，很适合被人信任。",
    traits: {
      rational: 78,
      emotional: 62,
      impulsive: 28,
      calm: 86,
      social: 72,
      solitary: 34,
      orderly: 91,
      rebellious: 39,
      ambitious: 58,
      altruistic: 96,
      humorous: 31,
      disguised: 12,
      moral: 99,
      conformist: 68,
      execution: 94,
      romance: 33,
      dependency: 18,
      realism: 71,
      absurdity: 6,
      courage: 99,
      egoism: 4,
      empathy: 88,
      decisiveness: 92,
      stressTolerance: 95
    }
  },
  {
    id: "conan",
    name: "柯南",
    originalName: "Conan Edogawa",
    source: "名侦探柯南",
    image: createCharacterPlaceholder("柯南", "#3b5aa3", "#d94b4b"),
    description: "你聪明、冷静、观察力强，遇到复杂局面时很快就会开始分析。你给人的感觉敏锐、可靠，还有点不好糊弄。",
    traits: {
      rational: 97,
      emotional: 42,
      impulsive: 26,
      calm: 89,
      social: 58,
      solitary: 61,
      orderly: 78,
      rebellious: 41,
      ambitious: 56,
      altruistic: 82,
      humorous: 24,
      disguised: 73,
      moral: 93,
      conformist: 52,
      execution: 91,
      romance: 21,
      dependency: 19,
      realism: 92,
      absurdity: 11,
      courage: 88,
      egoism: 14,
      empathy: 69,
      decisiveness: 94,
      stressTolerance: 93
    }
  },
  {
    id: "kaito_kid",
    name: "怪盗基德",
    originalName: "Kaito Kid",
    source: "名侦探柯南",
    image: createCharacterPlaceholder("怪盗基德", "#e8e8e8", "#2c3e73"),
    description: "你聪明、张扬、很会伪装，喜欢把事情做得漂亮又有戏剧感。你给人的感觉轻松、耀眼，还带点危险的从容。",
    traits: {
      rational: 84,
      emotional: 53,
      impulsive: 61,
      calm: 83,
      social: 91,
      solitary: 29,
      orderly: 47,
      rebellious: 79,
      ambitious: 72,
      altruistic: 58,
      humorous: 71,
      disguised: 99,
      moral: 61,
      conformist: 12,
      execution: 87,
      romance: 36,
      dependency: 11,
      realism: 68,
      absurdity: 48,
      courage: 92,
      egoism: 49,
      empathy: 57,
      decisiveness: 85,
      stressTolerance: 88
    }
  },
  {
    id: "count_of_monte_cristo",
    name: "基督山伯爵",
    originalName: "The Count of Monte Cristo",
    source: "基督山伯爵",
    image: createCharacterPlaceholder("基督山伯爵", "#3f4a5a", "#1c1a1a"),
    description: "冷静、隐忍、城府很深，做事很少只看眼前。你给人的感觉克制、危险，也很难被看透。",
    traits: {
      rational: 94,
      emotional: 58,
      impulsive: 11,
      calm: 96,
      social: 74,
      solitary: 72,
      orderly: 79,
      rebellious: 67,
      ambitious: 88,
      altruistic: 37,
      humorous: 18,
      disguised: 97,
      moral: 49,
      conformist: 14,
      execution: 96,
      romance: 41,
      dependency: 8,
      realism: 93,
      absurdity: 12,
      courage: 91,
      egoism: 78,
      empathy: 44,
      decisiveness: 95,
      stressTolerance: 97
    }
  },
  {
    id: "joseph_joestar",
    name: "乔瑟夫·乔斯达",
    originalName: "Joseph Joestar",
    source: "JOJO的奇妙冒险",
    image: createCharacterPlaceholder("乔瑟夫", "#8b6b3f", "#3a4a5a"),
    description: "很会随机应变。你给人的感觉不太正经，但关键时刻往往比谁都顶得住。",
    traits: {
      rational: 78,
      emotional: 67,
      impulsive: 71,
      calm: 62,
      social: 88,
      solitary: 24,
      orderly: 29,
      rebellious: 84,
      ambitious: 58,
      altruistic: 73,
      humorous: 95,
      disguised: 69,
      moral: 76,
      conformist: 12,
      execution: 74,
      romance: 44,
      dependency: 18,
      realism: 72,
      absurdity: 86,
      courage: 91,
      egoism: 46,
      empathy: 63,
      decisiveness: 82,
      stressTolerance: 85
    }
  },
  {
    id: "hannibal_lecter",
    name: "汉尼拔",
    originalName: "Hannibal Lecter",
    source: "汉尼拔",
    image: createCharacterPlaceholder("汉尼拔", "#5a4a42", "#1a1a1a"),
    description: "你冷静、聪明、很会观察别人，也很难被人真正看透。你给人的感觉优雅、克制，但危险感很重。",
    traits: {
      rational: 97,
      emotional: 36,
      impulsive: 8,
      calm: 98,
      social: 72,
      solitary: 78,
      orderly: 81,
      rebellious: 63,
      ambitious: 84,
      altruistic: 6,
      humorous: 41,
      disguised: 99,
      moral: 7,
      conformist: 9,
      execution: 95,
      romance: 12,
      dependency: 3,
      realism: 94,
      absurdity: 19,
      courage: 89,
      egoism: 92,
      empathy: 38,
      decisiveness: 96,
      stressTolerance: 99
    }
  },
  {
    id: "peter_griffin",
    name: "皮特·格里芬",
    originalName: "Peter Griffin",
    source: "恶搞之家",
    image: createCharacterPlaceholder("皮特", "#d8d8d8", "#4f8f5b"),
    description: "你是又蠢又坏的代名词。",
    traits: {
      rational: 14,
      emotional: 81,
      impulsive: 96,
      calm: 9,
      social: 86,
      solitary: 11,
      orderly: 4,
      rebellious: 72,
      ambitious: 18,
      altruistic: 29,
      humorous: 93,
      disguised: 6,
      moral: 23,
      conformist: 21,
      execution: 12,
      romance: 41,
      dependency: 62,
      realism: 5,
      absurdity: 99,
      courage: 57,
      egoism: 79,
      empathy: 24,
      decisiveness: 38,
      stressTolerance: 27
    }
  },
  {
    id: "brian_griffin",
    name: "布莱恩",
    originalName: "Brian Griffin",
    source: "恶搞之家",
    image: createCharacterPlaceholder("布莱恩", "#f2f2f0", "#b33a3a"),
    description: "神秘伪君子。",
    traits: {
      rational: 73,
      emotional: 66,
      impulsive: 49,
      calm: 58,
      social: 78,
      solitary: 36,
      orderly: 42,
      rebellious: 61,
      ambitious: 57,
      altruistic: 19,
      humorous: 69,
      disguised: 94,
      moral: 66,
      conformist: 78,
      execution: 31,
      romance: 74,
      dependency: 53,
      realism: 55,
      absurdity: 82,
      courage: 43,
      egoism: 82,
      empathy: 51,
      decisiveness: 47,
      stressTolerance: 39
    }
  },
  {
    id: "sonny_hayes",
    name: "桑尼·海耶斯",
    originalName: "Sonny Hayes",
    source: "F1：狂飙飞车",
    image: createCharacterPlaceholder("桑尼", "#c96b3b", "#1f2430"),
    description: "自信、老练、很抗压，越是危险和混乱的局面越能顶住。你给人的感觉松弛、强硬，还有种不好驯服的狠劲。",
    traits: {
      rational: 78,
      emotional: 57,
      impulsive: 63,
      calm: 88,
      social: 69,
      solitary: 52,
      orderly: 41,
      rebellious: 84,
      ambitious: 73,
      altruistic: 44,
      humorous: 61,
      disguised: 36,
      moral: 48,
      conformist: 9,
      execution: 91,
      romance: 18,
      dependency: 7,
      realism: 86,
      absurdity: 33,
      courage: 98,
      egoism: 71,
      empathy: 42,
      decisiveness: 95,
      stressTolerance: 99
    }
  },
  {
    id: "shaun_murphy",
    name: "肖恩医生",
    originalName: "Shaun Murphy",
    source: "良医",
    image: createCharacterPlaceholder("肖恩医生", "#6fa3c8", "#f3f5f7"),
    description: "理性、专注、真诚，做事很看重事实和细节。你给人的感觉安静、可靠，不太会拐弯，但往往能看到别人忽略的东西。",
    traits: {
      rational: 98,
      emotional: 34,
      impulsive: 16,
      calm: 82,
      social: 21,
      solitary: 88,
      orderly: 93,
      rebellious: 27,
      ambitious: 61,
      altruistic: 91,
      humorous: 9,
      disguised: 6,
      moral: 94,
      conformist: 63,
      execution: 89,
      romance: 82,
      dependency: 24,
      realism: 95,
      absurdity: 4,
      courage: 79,
      egoism: 11,
      empathy: 72,
      decisiveness: 84,
      stressTolerance: 86
    }
  },
  {
    id: "leon_kennedy",
    name: "李昂·肯尼迪",
    originalName: "Leon S. Kennedy",
    source: "生化危机",
    image: createCharacterPlaceholder("李昂", "#4f6272", "#2a2a2a"),
    description: "你冷静、能打、抗压强，遇到危险时往往越乱越稳。你给人的感觉可靠、利落，还有点疲惫型帅气。",
    traits: {
      rational: 82,
      emotional: 52,
      impulsive: 38,
      calm: 89,
      social: 61,
      solitary: 54,
      orderly: 68,
      rebellious: 49,
      ambitious: 57,
      altruistic: 84,
      humorous: 34,
      disguised: 21,
      moral: 87,
      conformist: 46,
      execution: 94,
      romance: 27,
      dependency: 10,
      realism: 88,
      absurdity: 9,
      courage: 97,
      egoism: 18,
      empathy: 72,
      decisiveness: 93,
      stressTolerance: 96
    }
  },
  {
    id: "ada_wong",
    name: "艾达·王",
    originalName: "Ada Wong",
    source: "生化危机",
    image: createCharacterPlaceholder("艾达", "#8b2e3b", "#1f1f1f"),
    description: "聪明、神秘、很会伪装，习惯把主动权抓在自己手里。你给人的感觉优雅、危险，也很难真正靠近。",
    traits: {
      rational: 91,
      emotional: 34,
      impulsive: 24,
      calm: 94,
      social: 73,
      solitary: 67,
      orderly: 63,
      rebellious: 71,
      ambitious: 76,
      altruistic: 29,
      humorous: 18,
      disguised: 99,
      moral: 38,
      conformist: 11,
      execution: 92,
      romance: 19,
      dependency: 4,
      realism: 93,
      absurdity: 12,
      courage: 88,
      egoism: 81,
      empathy: 37,
      decisiveness: 95,
      stressTolerance: 95
    }
  },
  {
    id: "chris_redfield",
    name: "克里斯",
    originalName: "Chris Redfield",
    source: "生化危机",
    image: createCharacterPlaceholder("克里斯", "#4d6b5f", "#20252b"),
    description: "硬、稳、责任感强，认定的事会一路顶到底。你给人的感觉可靠、强硬，还有种老兵式压迫感。",
    traits: {
      rational: 79,
      emotional: 43,
      impulsive: 34,
      calm: 87,
      social: 58,
      solitary: 63,
      orderly: 76,
      rebellious: 37,
      ambitious: 66,
      altruistic: 81,
      humorous: 15,
      disguised: 14,
      moral: 92,
      conformist: 62,
      execution: 97,
      romance: 9,
      dependency: 7,
      realism: 91,
      absurdity: 6,
      courage: 99,
      egoism: 16,
      empathy: 61,
      decisiveness: 96,
      stressTolerance: 99
    }
  },
  {
    id: "dio_brando",
    name: "迪奥",
    originalName: "Dio Brando",
    source: "JOJO的奇妙冒险",
    image: createCharacterPlaceholder("迪奥", "#c9a23a", "#4b2a63"),
    description: "你张扬、强势、野心很大，习惯把自己放在最上面。你给人的感觉耀眼、危险，还有种不讲道理的压迫感。",
    traits: {
      rational: 76,
      emotional: 58,
      impulsive: 62,
      calm: 79,
      social: 74,
      solitary: 49,
      orderly: 42,
      rebellious: 91,
      ambitious: 100,
      altruistic: 2,
      humorous: 27,
      disguised: 71,
      moral: 3,
      conformist: 4,
      execution: 92,
      romance: 6,
      dependency: 2,
      realism: 68,
      absurdity: 57,
      courage: 98,
      egoism: 100,
      empathy: 1,
      decisiveness: 97,
      stressTolerance: 94
    }
  },
  {
    id: "yoshikage_kira",
    name: "吉良吉影",
    originalName: "Yoshikage Kira",
    source: "JOJO的奇妙冒险",
    image: createCharacterPlaceholder("吉良吉影", "#8b7d6b", "#d4c7b0"),
    description: "你冷静、克制、很会隐藏自己，做事非常在意秩序和掌控感。你给人的感觉体面、安静，但越看越不对劲。",
    traits: {
      rational: 94,
      emotional: 22,
      impulsive: 9,
      calm: 97,
      social: 41,
      solitary: 83,
      orderly: 95,
      rebellious: 38,
      ambitious: 51,
      altruistic: 1,
      humorous: 6,
      disguised: 99,
      moral: 2,
      conformist: 71,
      execution: 93,
      romance: 0,
      dependency: 1,
      realism: 96,
      absurdity: 18,
      courage: 61,
      egoism: 96,
      empathy: 0,
      decisiveness: 91,
      stressTolerance: 98
    }
  },
  {
    id: "elon_musk",
    name: "一龙·马斯克",
    originalName: "Elon Musk",
    source: "现实人物",
    image: createCharacterPlaceholder("一龙", "#5b6673", "#1f2430"),
    description: "你点子多、行动猛、抗压强，喜欢折腾大项目，也不爱按常规出牌。你给人的感觉强势、跳脱，还有种停不下来的折腾劲。",
    traits: {
      rational: 84,
      emotional: 61,
      impulsive: 74,
      calm: 53,
      social: 72,
      solitary: 41,
      orderly: 37,
      rebellious: 95,
      ambitious: 100,
      altruistic: 34,
      humorous: 52,
      disguised: 29,
      moral: 31,
      conformist: 2,
      execution: 99,
      romance: 14,
      dependency: 9,
      realism: 88,
      absurdity: 57,
      courage: 97,
      egoism: 94,
      empathy: 23,
      decisiveness: 98,
      stressTolerance: 96
    }
  },
  {
    id: "tohsaka_rin",
    name: "远坂凛",
    originalName: "Rin Tohsaka",
    source: "Fate/stay night",
    image: createCharacterPlaceholder("远坂凛", "#c63f4a", "#1f2d63"),
    description: "聪明、要强、行动利落，表面上很稳，其实情绪和胜负心都不低, 但容易关键时候掉链子",
    traits: {
      rational: 88,
      emotional: 67,
      impulsive: 48,
      calm: 76,
      social: 73,
      solitary: 36,
      orderly: 74,
      rebellious: 57,
      ambitious: 82,
      altruistic: 71,
      humorous: 46,
      disguised: 58,
      moral: 79,
      conformist: 34,
      execution: 86,
      romance: 41,
      dependency: 22,
      realism: 81,
      absurdity: 18,
      courage: 84,
      egoism: 44,
      empathy: 68,
      decisiveness: 87,
      stressTolerance: 83
    }
  },
  {
    id: "asuka_langley",
    name: "明日香",
    originalName: "Asuka Langley Soryu",
    source: "新世纪福音战士",
    image: createCharacterPlaceholder("明日香", "#c94b3c", "#f0b23f"),
    description: "要强、嘴硬、好胜心重，表面很凶，其实情绪很敏感。你给人的感觉亮眼、带刺，也很难轻易服软。",
    traits: {
      rational: 62,
      emotional: 91,
      impulsive: 73,
      calm: 39,
      social: 76,
      solitary: 44,
      orderly: 58,
      rebellious: 71,
      ambitious: 88,
      altruistic: 41,
      humorous: 37,
      disguised: 54,
      moral: 49,
      conformist: 17,
      execution: 79,
      romance: 42,
      dependency: 74,
      realism: 57,
      absurdity: 29,
      courage: 84,
      egoism: 67,
      empathy: 46,
      decisiveness: 81,
      stressTolerance: 52
    }
  }





];

window.characters.forEach(function (character) {
  if (CHARACTER_IMAGE_MAP[character.id]) {
    character.image = CHARACTER_IMAGE_MAP[character.id];
  }
});
